@startuml

'++


box "Server Side" #LightBlue
	participant ServerApplication
	participant ServerSocket
	participant NewServerSocket
	participant Animal
end box

activate ServerApplication
activate ClientApplication
activate ServerSocket
ServerApplication -> ServerSocket: create

loop true

ServerApplication -> ServerSocket: listen

ClientApplication -> ClientSocket: create
activate ClientSocket
ClientApplication -> ClientSocket: connect

ClientSocket -> ServerSocket: connection request
ServerSocket -> NewServerSocket: create
activate NewServerSocket
NewServerSocket -> ClientSocket: connection established

loop 1:10

ClientApplication -> ClientSocket: writeObject
ClientSocket -> NewServerSocket: message
NewServerSocket -> ServerApplication: readObject()

alt object instanceof Animal
activate Animal

ServerApplication -> Animal: getAverageWeights()
Animal --> ServerApplication: return result
ServerApplication -> NewServerSocket: writeObject(result)

deactivate Animal
else object isn't Animal

ServerApplication -> NewServerSocket: writeObject(Exception)

end

NewServerSocket -> ClientSocket: message
ClientApplication -> ClientSocket: readObject
deactivate ClientSocket
deactivate NewServerSocket
end

end

@enduml